apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foobar
  namespace: foobar
spec:
  chart:
    spec:
      version: "2.0.0"
  values:
    replicaCount: 2
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
    ingress:
      hosts:
        - host: foobar.stage.local
          paths:
            - path: /
              pathType: ImplementationSpecific