apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foobar
  namespace: foobar
spec:
  releaseName: foobar
  chart:
    spec:
      chart: foobar
      sourceRef:
        kind: HelmRepository
        name: foobar
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx